Repository graciellehigino/ms_range_interactions, pull requests merged in 2022-11, with the labels that each got.

#91 Gbif exploration
  Manifest.toml
  Project.toml
  code/09-GBIF_data.jl
  figures/GBIF_years_1900.png
  figures/GBIF_years_1972.png
  figures/GBIF_years_total.png
Labels: enhancement, results, figure, review

#95 R2 methods
  manuscript.md
Labels: methods, review

#93 ✨ More on GBIF dates
  Manifest.toml
  Project.toml
  code/09-GBIF_data.jl
  code/10-GBIF_comparison.jl
  code/11-GBIF_doublecheck.jl
  code/A1_required.jl
  data/clean/gbif_ranges.tif
  figures/GBIF_years_1900.png
  figures/GBIF_years_1970.png
  figures/GBIF_years_prop_2000.png
  figures/GBIF_years_prop_nb_2000.png
  figures/GBIF_years_total.png
  figures/gbif_panels.png
  figures/gbif_range-diff.png
  figures/gbif_range-prop.png
  figures/ranges/iucn_gbifAcinonyx_jubatus.png
  figures/ranges/iucn_gbifAepyceros_melampus.png
  figures/ranges/iucn_gbifAlcelaphus_buselaphus.png
  figures/ranges/iucn_gbifCanis_aureus.png
  figures/ranges/iucn_gbifCanis_mesomelas.png
  figures/ranges/iucn_gbifCaracal_caracal.png
  figures/ranges/iucn_gbifConnochaetes_taurinus.png
  figures/ranges/iucn_gbifCrocuta_crocuta.png
  figures/ranges/iucn_gbifDamaliscus_lunatus.png
  figures/ranges/iucn_gbifEquus_quagga.png
  figures/ranges/iucn_gbifEudorcas_thomsonii.png
  figures/ranges/iucn_gbifGiraffa_camelopardalis.png
  figures/ranges/iucn_gbifHeterohyrax_brucei.png
  figures/ranges/iucn_gbifHippopotamus_amphibius.png
  figures/ranges/iucn_gbifKobus_ellipsiprymnus.png
  figures/ranges/iucn_gbifLeptailurus_serval.png
  figures/ranges/iucn_gbifLoxodonta_africana.png
  figures/ranges/iucn_gbifLycaon_pictus.png
  figures/ranges/iucn_gbifMadoqua_kirkii.png
  figures/ranges/iucn_gbifNanger_granti.png
  figures/ranges/iucn_gbifOurebia_ourebi.png
  figures/ranges/iucn_gbifPanthera_leo.png
  figures/ranges/iucn_gbifPanthera_pardus.png
  figures/ranges/iucn_gbifPapio_anubis.png
  figures/ranges/iucn_gbifPedetes_capensis.png
  figures/ranges/iucn_gbifPhacochoerus_africanus.png
  figures/ranges/iucn_gbifProcavia_capensis.png
  figures/ranges/iucn_gbifRedunca_redunca.png
  figures/ranges/iucn_gbifRhabdomys_pumilio.png
  figures/ranges/iucn_gbifSyncerus_caffer.png
  figures/ranges/iucn_gbifTragelaphus_oryx.png
  figures/ranges/iucn_gbifTragelaphus_scriptus.png
  figures/serval_gbif-figure.png
  figures/serval_mismatch_combined.png
  figures/serval_prey_mismatch.png
  figures/serval_prey_mismatch_buffered.png
  tables/gbif_difference.md
  tables/gbif_proportions.md
Labels: help wanted, figure, review

#96 overall edits
  manuscript.md
Labels: intro, results, review

#98 Review response letter
  manuscript.md
  metadata.json
  response-letter.md
Labels: documentation, todo :spiral_notepad:, review
